import { ArtifactType, ServiceDefinition } from './types';

export const SERVICES: Record<ArtifactType, ServiceDefinition[]> = {
  [ArtifactType.IP]: [
    { id: 'AbuseIPDB', name: 'AbuseIPDB', urlBuilder: (a) => `https://www.abuseipdb.com/check/${a}` },
    { id: 'AlienVault', name: 'AlienVault OTX', urlBuilder: (a) => `https://otx.alienvault.com/indicator/ip/${a}` },
    { id: 'ARIN', name: 'ARIN', urlBuilder: (a) => `https://search.arin.net/rdap/?query=${a}` },
    { id: 'BadPackets', name: 'Bad Packets', urlBuilder: (a) => `https://mirai.badpackets.net/?source_ip_address=${a}` },
    { id: 'Censys', name: 'Censys', urlBuilder: (a) => `https://search.censys.io/hosts/${a}` },
    { id: 'FortiGuard', name: 'FortiGuard', urlBuilder: (a) => `https://fortiguard.com/search?q=${a}&engine=8` },
    { id: 'GreyNoise', name: 'GreyNoise', urlBuilder: (a) => `https://viz.greynoise.io/ip/${a}` },
    { id: 'HackerTarget', name: 'HackerTarget', urlBuilder: (a) => `https://api.hackertarget.com/reverseiplookup/?q=${a}` },
    { id: 'IPinfo', name: 'IPinfo', urlBuilder: (a) => `https://ipinfo.io/${a}` },
    { id: 'IPQualityScore', name: 'IP Quality Score', urlBuilder: (a) => `https://www.ipqualityscore.com/free-ip-lookup-proxy-vpn-test/lookup/${a}` },
    { id: 'IPVoid', name: 'IPVoid', urlBuilder: (_) => `https://www.ipvoid.com/` },
    { id: 'MXToolbox', name: 'MX Toolbox', urlBuilder: (a) => `https://www.mxtoolbox.com/SuperTool.aspx?action=arin%3a${a}` },
    { id: 'Pulsedive', name: 'Pulsedive', urlBuilder: (a) => `https://pulsedive.com/indicator/?ioc=${btoa(a)}` },
    { id: 'Scamalytics', name: 'Scamalytics', urlBuilder: (a) => `https://scamalytics.com/ip/${a}` },
    { id: 'SecurityTrails', name: 'SecurityTrails', urlBuilder: (a) => `https://securitytrails.com/list/ip/${a}` },
    { id: 'Shodan', name: 'Shodan', urlBuilder: (a) => `https://www.shodan.io/host/${a}` },
    { id: 'Spyse', name: 'Spyse', urlBuilder: (a) => `https://spyse.com/target/ip/${a}` },
    { id: 'Talos', name: 'Talos', urlBuilder: (a) => `https://talosintelligence.com/reputation_center/lookup?search=${a}` },
    { id: 'ThreatCrowd', name: 'ThreatCrowd', urlBuilder: (a) => `https://www.threatcrowd.org/pivot.php?data=${a}` },
    { id: 'ThreatMiner', name: 'ThreatMiner', urlBuilder: (a) => `https://www.threatminer.org/host.php?q=${a}` },
    { id: 'TOR', name: 'TOR Relay', urlBuilder: (a) => `https://metrics.torproject.org/rs.html#search/${a}` },
    { id: 'URLhaus', name: 'URLhaus', urlBuilder: (a) => `https://urlhaus.abuse.ch/browse.php?search=${a}` },
    { id: 'VirusTotal', name: 'VirusTotal', urlBuilder: (a) => `https://www.virustotal.com/gui/ip-address/${a}` },
    { id: 'XForce', name: 'X-Force', urlBuilder: (a) => `https://exchange.xforce.ibmcloud.com/ip/${a}` },
  ],
  [ArtifactType.DOMAIN]: [
    { id: 'Alexa', name: 'Alexa', urlBuilder: (a) => `https://www.alexa.com/siteinfo/${a}` },
    { id: 'BlueCoat', name: 'BlueCoat', urlBuilder: (a) => `https://sitereview.bluecoat.com/#/lookup-result/${a}` },
    { id: 'Censys', name: 'Censys', urlBuilder: (a) => `https://search.censys.io/search?resource=hosts&q=${a}` },
    { id: 'FortiGuard', name: 'FortiGuard', urlBuilder: (a) => `https://fortiguard.com/search?q=${a}&engine=1` },
    { id: 'HostIo', name: 'host.io', urlBuilder: (a) => `https://host.io/${a}` },
    { id: 'MXToolbox', name: 'MX Toolbox', urlBuilder: (a) => `https://mxtoolbox.com/SuperTool.aspx?action=mx%3a${a}&run=toolpage` },
    { id: 'Pulsedive', name: 'Pulsedive', urlBuilder: (a) => `https://pulsedive.com/indicator/?ioc=${btoa(a)}` },
    { id: 'SecurityTrails', name: 'SecurityTrails', urlBuilder: (a) => `https://securitytrails.com/domain/${a}/dns` },
    { id: 'Shodan', name: 'Shodan', urlBuilder: (a) => `https://www.shodan.io/search?query=${a}` },
    { id: 'Spyse', name: 'Spyse', urlBuilder: (a) => `https://spyse.com/target/domain/${a}` },
    { id: 'Talos', name: 'Talos', urlBuilder: (a) => `https://talosintelligence.com/reputation_center/lookup?search=${a}` },
    { id: 'ThreatCrowd', name: 'ThreatCrowd', urlBuilder: (a) => `https://www.threatcrowd.org/pivot.php?data=${a}` },
    { id: 'ThreatMiner', name: 'ThreatMiner', urlBuilder: (a) => `https://www.threatminer.org/domain.php?q=${a}` },
    { id: 'URLhaus', name: 'URLhaus', urlBuilder: (a) => `https://urlhaus.abuse.ch/browse.php?search=${a}` },
    { id: 'URLVoid', name: 'URLVoid', urlBuilder: (a) => `https://urlvoid.com/scan/${a}` },
    { id: 'Unmask', name: 'Unmask Parasites', urlBuilder: (a) => `https://unmask.sucuri.net/security-report/?page=${a}` },
    { id: 'VirusTotal', name: 'VirusTotal', urlBuilder: (a) => `https://www.virustotal.com/gui/domain/${a}` },
    { id: 'XForce', name: 'X-Force', urlBuilder: (a) => `https://exchange.xforce.ibmcloud.com/url/${a}` },
  ],
  [ArtifactType.HASH]: [
    { id: 'AlienVault', name: 'AlienVault OTX', urlBuilder: (a) => `https://otx.alienvault.com/indicator/file/${a}` },
    { id: 'HybridAnalysis', name: 'Hybrid Analysis', urlBuilder: (a) => `https://www.hybrid-analysis.com/search?query=${a}` },
    { id: 'Talos', name: 'Talos', urlBuilder: (_) => `https://talosintelligence.com/talos_file_reputation` },
    { id: 'ThreatMiner', name: 'ThreatMiner', urlBuilder: (a) => `https://www.threatminer.org/sample.php?q=${a}` },
    { id: 'URLhaus', name: 'URLhaus', urlBuilder: (a) => `https://urlhaus.abuse.ch/browse.php?search=${a}` },
    { id: 'VirusTotal', name: 'VirusTotal', urlBuilder: (a) => `https://www.virustotal.com/gui/file/${a}` },
    { id: 'XForce', name: 'X-Force', urlBuilder: (a) => `https://exchange.xforce.ibmcloud.com/malware/${a}` },
  ],
  [ArtifactType.URL]: [
    { id: 'AnyRun', name: 'Any.Run', urlBuilder: (_) => `https://app.any.run/` },
    { id: 'BlueCoat', name: 'BlueCoat', urlBuilder: (_) => `https://sitereview.bluecoat.com/#/lookup-result/` },
    { id: 'FortiGuard', name: 'FortiGuard', urlBuilder: (a) => `https://fortiguard.com/search?q=${a}&engine=7` },
    { id: 'HackerTarget', name: 'HackerTarget', urlBuilder: (_) => `https://hackertarget.com/extract-links/` },
    { id: 'TrendMicro', name: 'TrendMicro', urlBuilder: (_) => `https://global.sitesafety.trendmicro.com/` },
    { id: 'URLhaus', name: 'URLhaus', urlBuilder: (a) => `https://urlhaus.abuse.ch/browse.php?search=${a}` },
    { id: 'URLScan', name: 'URLScan', urlBuilder: (_) => `https://urlscan.io/` },
    { id: 'URLVoid', name: 'URLVoid', urlBuilder: (a) => `https://urlvoid.com/scan/${a}` },
    { id: 'Unmask', name: 'Unmask Parasites', urlBuilder: (a) => `https://unmask.sucuri.net/security-report/?page=${a}` },
    { id: 'VirusTotal', name: 'VirusTotal', urlBuilder: (_) => `https://www.virustotal.com/gui/home/url` },
    { id: 'XForce', name: 'X-Force', urlBuilder: (a) => `https://exchange.xforce.ibmcloud.com/url/${a}` },
    { id: 'Zscaler', name: 'Zscaler', urlBuilder: (_) => `https://zulu.zscaler.com/` },
  ],
  [ArtifactType.UNKNOWN]: []
};